spring:
  profiles: local
  db1:
    datasource:
      url: jdbc:mysql://120.53.232.132:3306/cx-db?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
  db2:
    datasource:
      url: jdbc:sqlserver://120.53.232.132:1433;DatabaseName=mdp
      username: SA
      password: CX0524@2021
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
logging:
  config: classpath:logback-local.xml
server:
  port: 8090
